server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mtulkanov/java_inda_cloud_properties.git
        health:
          repositories:
            eureka:
              label: master
logging:
  level:
    root: info