swagger: "2.0"
info:
  description: "A service for product orders. It is a part of microservices mentoring program."
  version: "1.0.0"
  title: "Product Order"
paths:
  /order/{orderId}:
    get:
      summary: "Find product order by id"
      description: "Returns an order"
      parameters:
      - name: "orderId"
        in: "path"
        description: "An id of a product order"
        required: true
        type: "string"
      responses:
        200:
          description: OK
    