package com.mtulkanov.po.order;

import com.mtulkanov.po.clients.ProductSpecificationRepository;
import com.mtulkanov.po.exceptions.OrderNotFoundException;
import com.mtulkanov.po.kafka.Event;
import com.mtulkanov.po.kafka.KafkaService;
import com.mtulkanov.po.exceptions.EventNotRaisedException;
import com.mtulkanov.po.exceptions.SpecificationNotFoundException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.kafka.support.SendResult;
import org.springframework.stereotype.Service;
import org.springframework.util.concurrent.FailureCallback;
import org.springframework.util.concurrent.SuccessCallback;

import java.util.Optional;

/**
 * TODO: This is autogenerated Java-Doc.
 *
 * @author Nikita_Puzankov
 */
@Service
@Slf4j
@RequiredArgsConstructor
public class ProductOrderServiceImpl implements ProductOrderService {
    private final ProductOrderRepository orderRepository;
    private final ProductSpecificationRepository specificationRepository;
    private final KafkaService kafkaService;

    public ProductOrder orderProductBySpecificationId(String specificationId) {
        if (specificationRepository.existsById(specificationId) == null) {
            String message = "There is no product specification with Id: " + specificationId;
            log.error(message);
            throw new SpecificationNotFoundException(message);
        }
        ProductOrder productOrder = new ProductOrder(
                null,
                specificationId,
                1L,
                ProductOrder.SUSPENDED
        );
        productOrder = orderRepository.save(productOrder);
        log.info("Created {}", productOrder);
        final Long orderId = productOrder.getId();
        try {
            SuccessCallback<SendResult<String, Event>> successCallback = sendResult ->
                    log.info(
                            "Event OrderCreated for order {} successfully saved to kafka",
                            orderId
                    );
            FailureCallback failureCallback = ex -> rejectOrder(orderId);
            kafkaService.orderCreated(productOrder, successCallback, failureCallback);
        } catch (EventNotRaisedException exception) {
            log.error("Could not raise OrderCreated event", exception);
            productOrder.setStatus(ProductOrder.REJECTED);
            orderRepository.save(productOrder);
        }
        return productOrder;
    }

    public ProductOrder rejectOrder(Long orderId) {
        Optional<ProductOrder> orderOptional = orderRepository.findById(orderId);
        orderOptional.ifPresent(order -> order.setStatus(ProductOrder.REJECTED));
        return orderOptional.orElseThrow(OrderNotFoundException::new);
    }
}
