package com.mtulkanov.po.order;

import lombok.AllArgsConstructor;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * TODO: This is autogenerated Java-Doc.
 *
 * @author Nikita_Puzankov
 */
@Document
@Data
@AllArgsConstructor
public class ProductOrder {
    public static final String REJECTED = "REJECTED";
    public static final String SUSPENDED = "SUSPENDED";

    @Id
    private String id;
    private String specificationId;
    private Long quantity;
    private String status;
}
